### ISSUE TITLE
How to measure the diversity of stored data?

### ISSUE THREAD

**Issue by shdotcom** [ValentinOsunaEnciso/2022_AdiversityMetric#1]
Hi, 
I have a .mat which represents the outputs of an optimization algorithm. This file includes the solutions obtained at each iteration, where the pop_size =100; dimension=5 and max_iteration=500.
Could you please provide an example shows how to use the current code measure the diversity of the population of solutions at each iteration? Is it by calling the nVOL2(X,l,u) function; or it requires some modifications?

Also, could you please add another example about how to use this DM with a Metaheuristic like PSO.

Thank you

**Comment by ValentinOsunaEnciso** [comment]
Hi sh,
it is unnecessary to modify the function, you can apply it as is. Let's consider the next example, where we have a population X of 3 individuals and four dimensions:

X=[x_11, x_12, x_13, x_14;
      x_21, x_22, x_23, x_24
      x_31, x_32, x_33, x_34]
l=[-50.0, -50.0, -50.0, -50.0]
u=[50.0, 50.0, 50.0, 50.0]

The containers 'u' and 'l' are 1xD in size, where D is the dimension of the problem, whereas X is Np x D, where Np is the population size.

I hope this help. 
Regards,

Valentin Osuna Enciso

**Comment by shdotcom** [comment]
Thank you for your reply. That was very useful. I will use this metric in my paper.
